version: "3"
services:
    web:
      image: somkiat/web:2.0
      build:
        context: ./front
        dockerfile: Dockerfile
      ports:
        - 9999:80
    db:
      image: mysql:8.0.29
      environment:
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
        - MYSQL_DATABASE=demo
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pass
            
