version: "3"
services:
    web:
      image: somkiat/web:2.0
      build:
        context: ./front
        dockerfile: Dockerfile
      ports:
        - 9999:80
      depends_on:
        db2:
          condition: service_healthy
    db:
      image: mysql:8.0.29
      environment:
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
        - MYSQL_DATABASE=demo
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pass
    db2:
      image: postgres:10.14
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      healthcheck:
        test: ["CMD-SHELL", "pg_isready  -d postgres -U postgres"]
        interval: 10s
        timeout: 10s
        retries: 5
            
