FROM node:16-alpine3.15 AS step1
WORKDIR /work
COPY . .
RUN npm install
RUN npm run build #/work/dist/demo-angular

FROM httpd:2.4
COPY --from=step1 /work/dist/demo-angular /usr/local/apache2/htdocs/
